### ISSUE TITLE
Tutorial steps seems to be inaccurate

### ISSUE THREAD

**Issue by harpreetpaul** [GoogleCloudPlatform/cloud-deploy-tutorials#1]
I am following this [tutorial guide](https://github.com/GoogleCloudPlatform/cloud-deploy-tutorials/blob/main/walkthroughs/cloud_deploy_e2e_gke/cloud_deploy_e2e_gke.md) to try cloud deploy. 

The steps mentioned in the readme and corresponding GitHub folder structure does not seem to match.

The [section](https://github.com/GoogleCloudPlatform/cloud-deploy-tutorials/blob/main/walkthroughs/cloud_deploy_e2e_gke/cloud_deploy_e2e_gke.md#building-with-skaffold
) states that ``web`` directory will contain ``skaffold.yaml``, but there is no such yaml file and subsequently the following commands are failing. Please update the documentation or add the missing file.

**Comment by henrybell** [comment]
Hi,

Thanks for opening the issue -- there are several factors to investigate here:

- Are you launching the tutorial from the links [here](https://cloud.google.com/deploy/docs/tutorials)? Accessing the tutorial in this way triggers some automated steps that clone that repository and launch the Cloud Shell environment in your browser, ready for the tutorial steps, so that is the recommended way to get up and running.

- The file `web/skaffold.yaml` is created by the `bootstrap.sh` setup script from a template as one of the final steps [here](https://github.com/GoogleCloudPlatform/cloud-deploy-tutorials/blob/91816234463598ebd9c4a5c11e8ae5e74e938303/bootstrap.sh#L123), so if the script did not successfully complete (due to permissions or other issues), then it's possible this file could not have been created. After the `bootstrap.sh` script has completed, are you able to successfully `cat web/skaffold.yaml` in your Cloud Shell environment?

- When you start the tutorial using one of the links [here](https://cloud.google.com/deploy/docs/tutorials), this repository is automatically cloned into the Cloud Shell filesystem, under `$HOME/cloudshell-open/`. If you've started (or restarted) the tutorial more than once, a new copy of the repository will be cloned each time in this location, into `$HOME/cloudshell-open/cloud-deploy-tutorials-X`. This could mean that the setup script has run and the `skaffold.yaml` file has been created in one of those cloned repositories, but that clone is not the one being used (if the Cloud Shell session has timed out, for example, and the tutorial was resumed/restarted at a later time).

If you're able to update this issue with your progress, that would be much appreciated. Thanks!

**Comment by harpreetpaul** [comment]
Thank you Henry for the details response. 

I am not launching the tutorial in the cloud shell or from the links [here](https://cloud.google.com/deploy/docs/tutorials). 

I have directly cloned this repo in my local and will changed the configurations to target tutorial to my existing GKE clusters. I will go through the ``bootstrap.sh``, and will either modify the contents in file or will create necessary configurations  manfully.
